### ISSUE TITLE
todo-list:

### ISSUE THREAD

**Issue by LichKing112** [ExynosNetwork/exynosnetwork.github.io#3]
### todo-list:

- [x] rework the site (july rework)
- [ ] add gallery (video previews, screenshots, and caraousel)
- [x] re arrenge css hierarchy
- [x] switch to saas/scss
- [x] legacy sites (past reworks for you)

everything else tba
